### ISSUE TITLE
Unexpected keyword "workers" (scipy)

### ISSUE THREAD

**Issue by lazadiris** [pglira/simpleICP#26]
I installed the SimpleICP package with pip (python), and tested the code presented in the documentation. And now I had this problem. Can you help me please ?
![image](https://user-images.githubusercontent.com/99643277/160442298-9181213a-a5a3-4890-a49c-66ca9af14449.png)

**Comment by pglira** [comment]
You're probably using an old scipy version. Previous to version 1.6 the parameter "workers" was called "n_jobs", see [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.cKDTree.query.html):
![image](https://user-images.githubusercontent.com/14214284/160546718-d4bc7cff-af87-44cf-822e-40f9f4199db4.png)

Can you check your scipy version with ``pip show scipy``?

**Comment by lazadiris** [comment]
It worked. Thank you so much.
The error no longer appeared.
![image](https://user-images.githubusercontent.com/99643277/161937847-47c0c554-b94e-4703-99db-e23d95767c08.png)

**Comment by pglira** [comment]
Great! 
.
