### ISSUE TITLE
(Python) Singular matrix

### ISSUE THREAD

**Issue by smiles724** [pglira/simpleICP#30]
Hi, thanks for offering this sort of convenient implementation. However, I randomly made some inputs, and often found that it reported the error of singular matrix. See below. 
![image](https://user-images.githubusercontent.com/39299863/192290523-56271699-5c36-406b-8432-06aca6990405.png)

**Comment by pglira** [comment]
Hi, the issue here is that to few correspondences remain. As a general rule of thumb, you should have at least approx. 100 correspondences in the first iteration.

I will add an appropriate error message to make this more clearer for the user.
