### ISSUE TITLE
Calculation of RMSE between point clouds

### ISSUE THREAD

**Issue by jkissi** [pglira/simpleICP#33]
Hi! 
I am attempting to detect differences between multiple clouds. I am afraid that I am a little confused...does your [python] implementation generate any products that would allow me to calculate the RMSE between the final estimation given by the algo and my target cloud. What I am looking for are the **_inlier correspondences_** and I am unsure of how to generate them/find them from the outputs. 

Apologies if it obvious, I would be very grateful if you could point it out to me, or if there is a process involved, give me a run down of what I need to do. 

Cheers and thanks in advance,
J

**Comment by pglira** [comment]
Hi! The closest that you can get at the moment is the standard deviation of the point-to-plane distances:
![image](https://user-images.githubusercontent.com/14214284/226255669-0247173b-ed88-4ae2-93e0-7990998a155c.png)
In this case the number of inlier correspondences as determined by the algorithm is 752.
Hope this helps.

**Comment by jkissi** [comment]
Hi, Thanks this is really helpful! It was kinda obvious, I just didn't see it. Thanks for the clarification.
Does the iteration table with the correspondences and std residuals get output as a textfile or in another product?

thanks 
j

**Comment by jkissi** [comment]
> Hi! The closest that you can get at the moment is the standard deviation of the point-to-plane distances: ![image](https://user-images.githubusercontent.com/14214284/226255669-0247173b-ed88-4ae2-93e0-7990998a155c.png) In this case the number of inlier correspondences as determined by the algorithm is 752. Hope this helps.

Hi again!! Sorry but could you just confirm for me whether this information is passed to one of the output products or if it is only written to the console? Being able to grab that information and pass it to a function I've written would help me alot, so it would be good to know for sure one way or the other. 

Cheers again
j

**Comment by pglira** [comment]
The final point-to-plane distances are now returned by the function, see commit 283143c

With this, you can run now run:

```python
H, X_mov_transformed, rbp, distance_residuals = icp.run(max_overlap_distance=1)
```

and calculate all you need with

```python
len(distance_residuals) # number of correspondences
np.mean(distance_residuals)
np.std(distance_residuals)
```

Hope this helps.

**Comment by pglira** [comment]
It's already closed. 😊

**Comment by jkissi** [comment]
Haha, didn't even see that!
