### ISSUE TITLE
using in unity

### ISSUE THREAD

**Issue by Ademord** [pglira/simpleICP#4]
hello, i want to aggregate depth scans from a game camera in Unity. 

Do you have an implementation in C# i could use or is there any way I could use your code? I reaaaally need to do this and I don't understand other tutorials out there. 

Every 10 frames I would make a "picture" and get the depth from the camera, then I would turn that into a point cloud and use for example your implementation to make a point cloud of my scene. 

I hope you can help me @pglira

**Comment by pglira** [comment]
Sorry, a C# implementation is not planned at the moment.
