### ISSUE TITLE
Displaying the corresponding point clouds in open3D after each iteration

### ISSUE THREAD

**Issue by rllyryan** [pglira/simpleICP#5]
Dear pglira,

Your work is amazingly concise and neat!

Could I also find out how do you display the point clouds after each iteration? (Do you use open3d to visualise the point clouds?)

Thank you for you time!

Regards,
rllyryan

**Comment by pglira** [comment]
The easiest way is to write an xyz file after each iteration and visualize them afterwards with open3d.

**Comment by pglira** [comment]
Duplicate of #7
